language: node_js

node_js:
  - "8"

jdk:
  - oraclejdk8

git:
  submodules: false

script:
  - ./sonarts-core/travis.sh
  - ./sonarts-sq-plugin/travis.sh

cache: # yarn
  directories:
    - '$HOME/.m2/repository'    
  before_cache:
    - rm -rf $HOME/.m2/repository/org/sonarsource/typescript
    - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

notifications:
  email: false
  webhooks:
    - secure: "f77xo3BmGOrcSuyBzzubElPZ2BdewFfQFR1CgbkaybVWVUVwJB/2FHCK6M6CQ+EkjPjubnADe5L/bgyU2R6Q6+dWLluX8K69pbsb34wJvNNfvyVnKbdGnmn6PYzsJoEi2do+JujbTqPcAfkYb0NyEZ4BkoSbamcrxMhKTSbNa9bXI9mT6Fx4dXSFocxybdS1wlOEDyAps3BbLmFlPbm2LsrEWZFF0w8lemNw4vcFbDrA4xYX10G0/MUw1DF4sno/pS71J6qD0Ftivt8PJfS1bpnZHIi2B44EbKAb5qU0JGi5tf7/iRjH6V5XyKgJ+D7Ug/MQ7X7S24i3CIde+TqbY6ZV3MNNlsx35mBarQ7eBpS6M0wlnHyZVHIT8inIYMYDHK1dE3lwNzYLs0pScUQZXwfE/GK64J/D8l1qC51eLGu5IfPnuT2luBu/16lxVtUey6V5ldxA2BgJTEeDJuQ4dag66198HA4cdMA2kOAyDpKcWuSwz7AUSkXAoBqSaVix3BvtvsXefRctH7d7jhkV/BUOdvVW4pUZThCQevZ65a3wWd+383W+RbfGse+q4BxCJOvgfSYv3f6gKWc/IA7eVrf/5z+eM+/+2QHfktx9//18bYeeFjqhxrcxgNiOeSwz+n8tMnrB5JO0Qc1kkuabtzbaqK33ph1wsQ+2yfJa9TU="
  on_start: always
